hide_download: true
hide_download_original: null
leftnav:
- identifier: 82f65182-4c6c-e3b4-291b-31e2cb107072
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: e3ce942a-a63d-d6df-1cca-0a3da755376f
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: df9f4cc9-a4d0-6c27-518b-604d3ed210bd
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 61e0cf49-6994-c6b1-2eed-69b01ae5286c
  name: Assignments
  pageRef: /pages/assignments/
  weight: 40
- identifier: 2558c0e7-6169-0752-7e54-8b43d1a9338e
  name: Document Report
  pageRef: /pages/assignments/document-report
  parent: 61e0cf49-6994-c6b1-2eed-69b01ae5286c
  weight: 50
- identifier: b97ae073-fe7f-a976-70c6-991f8b75037a
  name: Artifact/Plan Report
  pageRef: /pages/assignments/artifact-plan-report
  parent: 61e0cf49-6994-c6b1-2eed-69b01ae5286c
  weight: 60
- identifier: d853c143-c3a5-71b7-6453-5282dcc9b8ce
  name: Final Project
  pageRef: /pages/assignments/final-project
  parent: 61e0cf49-6994-c6b1-2eed-69b01ae5286c
  weight: 70
